### ISSUE TITLE
HTTP GET variable for searching

### ISSUE THREAD

**Issue by karlek** [datasektionen/zfinger#1]
Would be quite nice to have a URL variable called __q__ so we could do searches like: `https://zfinger.datasektionen.se/?q=jbrann`.

Which would give us this search request: 
![out14998](https://cloud.githubusercontent.com/assets/1278705/13163399/fca6c8f6-d6ac-11e5-925f-e3d030323a5c.png)

This is useful for scripting / firefox bookmark keywording / etc.

**Comment by addem1234** [comment]
Sound like a good idea. Solved with 61778c62bb0a9e9407d58aa04de2fd5ddeaadc4b
