### ISSUE TITLE
Missing results on search 

### ISSUE THREAD

**Issue by karlek** [datasektionen/zfinger#2]
When searching for Linn: `https://zfinger.datasektionen.se/?q=linn`
And when searching for Bergelid: `https://zfinger.datasektionen.se/?q=bergelid`

Linn Bergelid is only in the Bergelid-query, which is erroneous.
Haha, konstigaste issuen :camel: :cactus: :dancer: :dancers: :8ball:

**Comment by addem1234** [comment]
KTHs LDAP server returns at most 10 results, so paged results would have to
be implemented.
Typ jobbigt osv

**Comment by karlek** [comment]
Can't we just repeat the query?

If there are 1k results we do 100 queries before showing the page, so instead of implementing pagination we just return a __huge__ list of results. Would that work?

**Comment by addem1234** [comment]
It would work, yes, I even tried it once. The loading time ended up being
crazy long though so I stashed it... A possible solution would be to cache
the results locally so that searches can still be quick.

**Comment by karlek** [comment]
Can we enumerate their database? Like searching for empty string gives us all results?

**Comment by LudwikJaniuk** [comment]
I think correct results are more important than fast results. Could you implement the changes you stashed, maybe on an optional api endpoint? Also, probably there won't always be 1000 results...

**Comment by macfeaster** [comment]
Search results have been greatly expanded, and are now cached.
