### ISSUE TITLE
Stor & Liten

### ISSUE THREAD

**Issue by Plongy** [datasektionen/zfinger#3]
Urlen för att hämta en bild är case-sensitive, det är ju lite trist när användare är keffa och skriver in keffa kth-id:n

Jämför skönheten i dessa bilder:
![https://zfinger.datasektionen.se/user/Jespel/image/](https://zfinger.datasektionen.se/user/Jespel/image/)
![https://zfinger.datasektionen.se/user/jespel/image/](https://zfinger.datasektionen.se/user/jespel/image/)

**Comment by addem1234** [comment]
closed by edbe262
